# It does magic only if there is package.json file in the root of the project
name: PR testing - if Node project

on:
  pull_request_target:
    types: [opened, reopened, synchronize, ready_for_review]
  push:
    branches: ['*']

jobs:
  test-nodejs-pr:
    name: Test NodeJS PR - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13, windows-latest]
    env:
      CYPRESS_CACHE_FOLDER: ${{ startsWith(matrix.os, 'macos') && '$HOME/Library/Caches/Cypress' || startsWith(matrix.os, 'windows') && '$HOME/AppData/Local/Cypress/Cache' || '$HOME/.cache/Cypress' }}
    steps:
      - if: >
          !github.event.pull_request.draft && !(
            (github.actor == 'asyncapi-bot' && (
              startsWith(github.event.pull_request.title, 'ci: update of files from global .github repo') ||
              startsWith(github.event.pull_request.title, 'chore(release):')
            )) ||
            (github.actor == 'asyncapi-bot-eve' && (
              startsWith(github.event.pull_request.title, 'ci: update of files from global .github repo') ||
              startsWith(github.event.pull_request.title, 'chore(release):')
            )) ||
            (github.actor == 'allcontributors[bot]' &&
              startsWith(github.event.pull_request.title, 'docs: add')
            )
          )
        id: should_run
        name: Should Run
        run: echo "shouldrun=true" >> $GITHUB_OUTPUT
        shell: bash
      - if: steps.should_run.outputs.shouldrun == 'true'
        name: Set git to use LF #to once and for all finish neverending fight between Unix and Windows
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
        shell: bash
      - if: steps.should_run.outputs.shouldrun == 'true'
        name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Checkout the merge commit instead of the pull request head commit for a pull request
          # Fallback to the head commit if its not a pull request
          ref: ${{ github.event.pull_request.number != '' && format('refs/pull/{0}/merge', github.event.pull_request.number) || github.ref }}

      - if: steps.should_run.outputs.shouldrun == 'true'
        name: Check if Node.js project and has package.json
        id: packagejson
        run: test -e ./package.json && echo "exists=true" >> $GITHUB_OUTPUT || echo "exists=false" >> $GITHUB_OUTPUT
        shell: bash
      - if: steps.packagejson.outputs.exists == 'true'
        name: Check if .nvmrc exists
        id: nvmrc
        run: test -e .nvmrc && echo "exists=true" >> $GITHUB_OUTPUT || echo "exists=false" >> $GITHUB_OUTPUT
        shell: bash
      - if: steps.nvmrc.outputs.exists == 'true'
        name: Read Node.js version from .nvmrc
        id: nodeversion
        run: echo "version=$(cat .nvmrc)" >> $GITHUB_OUTPUT
        shell: bash
      - if: steps.packagejson.outputs.exists == 'true' && steps.nvmrc.outputs.exists == 'true'
        name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '${{ steps.nodeversion.outputs.version }}'
      - if: steps.packagejson.outputs.exists == 'true'
        name: Install dependencies
        run: npm ci
      - if: steps.packagejson.outputs.exists == 'true'
        name: Test
        run: npm test --if-present
      - if: steps.packagejson.outputs.exists == 'true' && matrix.os == 'ubuntu-latest'
        name: Run linter
        run: npm run lint --if-present
      - if: steps.packagejson.outputs.exists == 'true'
        name: Run release assets generation to make sure PR does not break it
        shell: bash
        run: npm run generate:assets --if-present
      - name: Cache Cypress binary
        uses: actions/cache@v4   # v4 supports Node 20-based runners
        if: steps.packagejson.outputs.exists == 'true'
        with:
          path: |
            ~/.cache/Cypress
            ~/Library/Caches/Cypress
            ~/AppData/Local/Cypress/Cache
          key: cypress-cache-${{ matrix.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            cypress-cache-${{ matrix.os }}-
      - name: Install Cypress Binary
        if: steps.packagejson.outputs.exists == 'true'
        run: npx cypress install
        env:
          CYPRESS_CACHE_FOLDER: ${{ env.CYPRESS_CACHE_FOLDER }}
   
      - if: steps.should_run.outputs.shouldrun == 'true' && steps.packagejson.outputs.exists == 'true'
        name: Run Cypress E2E Tests
        uses: cypress-io/github-action@6c143abc292aa835d827652c2ea025d098311070
        with:
          start: npm run dev
          wait-on: 'http://localhost:3000'  # Adjust port as needed
          wait-on-timeout: 120
          install: true

     